#!/bin/bash

set -euo pipefail

NAMES=~/.shoved.names
VERSION=0.3.1

do_setup() {
    cat <<\!
        d()  { eval "$(shoved chdir $1)"; }
        dl() { eval "dirs -v"; }
        dn() { eval "$(shoved name "$1" $(dirs))"; }
        dp() { eval "$(shoved pushpop "$1")"; }
        dx() { eval "$(shoved exch)"; }
        ds() { eval "$(shoved setup)"; }
!
    for i in $(seq 0 9); do
        echo "alias $i='d $i'"
    done
}

do_chdir() {
    if [[ $1 == "" ]]; then
        echo 'echo "Missing directory index or name" >&2'
    elif [[ $1 =~ ^[0-9]$ ]]; then
        # d N does pushd +N
        _move "pushd +$1" ""
    else
        _move "cd %s" $1
    fi
}

do_exch() {
    _move "pushd" ""
}

do_pushpop() {
    if [[ $1 == "" ]]; then
        _move "popd" ""
    else
        _move "pushd %s" $1
    fi
}

do_name() {
    if [[ $1 == "" ]]; then
        if [[ -e $NAMES ]]; then
            local maxlen=$(awk '{ x = x > length($1) ? x : length($1) } END { print x }' <$NAMES)
            echo "awk '{ printf(\" %-${maxlen}s  %s\\n\", \$1, \$2) }' <$NAMES | sort -k1"
        else
            echo "echo '$NAMES not found' >&2"
        fi
    else
        if [[ -e $NAMES ]]; then
            local temp=$(mktemp /tmp/shoved.XXXXX)
            trap "rm -f $temp" RETURN
            cp $NAMES $temp
            awk "\$1 != \"$1\"" <$temp >$NAMES
        fi
        echo "$1 $2" >>$NAMES
        echo "echo ' $1  $2'"
    fi
}

do_version() {
    echo $VERSION
}

_chdir_or_pushd() {
    local target="$(_resolve $2)"
    if [[ $target == "" ]]; then
        target="$2"
    fi
    echo "$1 $target >/dev/null && dirs -v | sed -n '1s/0 *//p'"
}

_move() {
    local command
    if [[ $2 != "" ]]; then
        target="$(_resolve "$2")
}
        echo "popd >/dev/null && dirs -v | sed -n '1s/0 *//p'"

_resolve() {
    local target
    if [[ ${SHOVED_RESOLVER:-} != "" ]]; then
        target=$($SHOVED_RESOLVER resolve $1)
        if [[ $? != 0 ]]; then
            echo __ERROR__
            return
        elif [[ $target != "" ]]; then
            echo "$target"
            return
        fi
    fi
    target=$(awk "\$1 == \"$1\" { print \$2; exit(0) }" <$NAMES)
    if [[ $target != "" ]]; then
        echo "$target"
    fi
}

command="$1"
shift

if [[ $command =~ ^(chdir|exch|name|pushpop|setup|version)$ ]]; then
    do_$command "$@"
else
    echo "echo 'Invalid command: $command' >&2; false"
fi

